//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandyControl.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandyControl.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上午.
        /// </summary>
        public static string Am {
            get {
                return ResourceManager.GetString("Am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭所有.
        /// </summary>
        public static string CloseAll {
            get {
                return ResourceManager.GetString("CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭其他.
        /// </summary>
        public static string CloseOther {
            get {
                return ResourceManager.GetString("CloseOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误的图片路径.
        /// </summary>
        public static string ErrorImgPath {
            get {
                return ResourceManager.GetString("ErrorImgPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非法的图片尺寸.
        /// </summary>
        public static string ErrorImgSize {
            get {
                return ResourceManager.GetString("ErrorImgSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格式错误.
        /// </summary>
        public static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 间隔10分钟.
        /// </summary>
        public static string Interval10m {
            get {
                return ResourceManager.GetString("Interval10m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 间隔1小时.
        /// </summary>
        public static string Interval1h {
            get {
                return ResourceManager.GetString("Interval1h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 间隔1分钟.
        /// </summary>
        public static string Interval1m {
            get {
                return ResourceManager.GetString("Interval1m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 间隔2小时.
        /// </summary>
        public static string Interval2h {
            get {
                return ResourceManager.GetString("Interval2h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 间隔30分钟.
        /// </summary>
        public static string Interval30m {
            get {
                return ResourceManager.GetString("Interval30m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 间隔30秒.
        /// </summary>
        public static string Interval30s {
            get {
                return ResourceManager.GetString("Interval30s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 间隔5分钟.
        /// </summary>
        public static string Interval5m {
            get {
                return ResourceManager.GetString("Interval5m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能为空.
        /// </summary>
        public static string IsNecessary {
            get {
                return ResourceManager.GetString("IsNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳转.
        /// </summary>
        public static string Jump {
            get {
                return ResourceManager.GetString("Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找类似 {0} 的本地化字符串。.
        /// </summary>
        public static string LangComment {
            get {
                return ResourceManager.GetString("LangComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 杂项.
        /// </summary>
        public static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一页.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无数据.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不在范围内.
        /// </summary>
        public static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面模式.
        /// </summary>
        public static string PageMode {
            get {
                return ResourceManager.GetString("PageMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下午.
        /// </summary>
        public static string Pm {
            get {
                return ResourceManager.GetString("Pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG图片.
        /// </summary>
        public static string PngImg {
            get {
                return ResourceManager.GetString("PngImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一页.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 滚动模式.
        /// </summary>
        public static string ScrollMode {
            get {
                return ResourceManager.GetString("ScrollMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过大.
        /// </summary>
        public static string TooLarge {
            get {
                return ResourceManager.GetString("TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 双页模式.
        /// </summary>
        public static string TwoPageMode {
            get {
                return ResourceManager.GetString("TwoPageMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知大小.
        /// </summary>
        public static string UnknownSize {
            get {
                return ResourceManager.GetString("UnknownSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 放大.
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩小.
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }

        #region Flag 日历控件增强

        /// <summary>
        /// Looks up a localized string similar to  今天
        /// </summary>
        public static string Today
        {
            get
            {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  昨天
        /// </summary>
        public static string Yesterday
        {
            get
            {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  明天
        /// </summary>
        public static string Tomorrow
        {
            get
            {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  本周
        /// </summary>
        public static string ThisWeek
        {
            get
            {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  上周
        /// </summary>
        public static string LastWeek
        {
            get
            {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  下周
        /// </summary>
        public static string NextWeek
        {
            get
            {
                return ResourceManager.GetString("NextWeek", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  周一
        /// </summary>
        public static string Monday
        {
            get
            {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  周日
        /// </summary>
        public static string Sunday
        {
            get
            {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  本月
        /// </summary>
        public static string ThisMonth
        {
            get
            {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  上月
        /// </summary>
        public static string LastMonth
        {
            get
            {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  下月
        /// </summary>
        public static string NextMonth
        {
            get
            {
                return ResourceManager.GetString("NextMonth", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  月初
        /// </summary>
        public static string MonthBegin
        {
            get
            {
                return ResourceManager.GetString("MonthBegin", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  月末
        /// </summary>
        public static string MonthEnd
        {
            get
            {
                return ResourceManager.GetString("MonthEnd", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  今年
        /// </summary>
        public static string ThisYear
        {
            get
            {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  去年
        /// </summary>
        public static string LastYear
        {
            get
            {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  明年
        /// </summary>
        public static string NextYear
        {
            get
            {
                return ResourceManager.GetString("NextYear", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  年初
        /// </summary>
        public static string YearBegin
        {
            get
            {
                return ResourceManager.GetString("YearBegin", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  年末
        /// </summary>
        public static string YearEnd
        {
            get
            {
                return ResourceManager.GetString("YearEnd", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  00:00:00
        /// </summary>
        public static string DayTimeBegin
        {
            get
            {
                return ResourceManager.GetString("DayTimeBegin", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  当前时间
        /// </summary>
        public static string DayTimeNow
        {
            get
            {
                return ResourceManager.GetString("DayTimeNow", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to  23:59:59
        /// </summary>
        public static string DayTimeEnd
        {
            get
            {
                return ResourceManager.GetString("DayTimeEnd", resourceCulture);
            }
        }
        #endregion Flag 日历控件增强
    }
}
